{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.secret.googleClientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secret.googleClientSecret | b64enc }}
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
  NOTION_INTEGRATION_TOKEN: {{ .Values.secret.notionIntegrationToken | b64enc }}
  S3_ACCESS_KEY: {{ .Values.secret.s3AccessKey | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.s3AccessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.secret.s3SecretKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.s3SecretKey | b64enc }}
  WEAVIATE_API_KEY: {{ .Values.secret.weaviateApiKey | b64enc }}
  RESEND_API_KEY: {{ .Values.secret.resendApiKey | b64enc }}
  SMTP_PASSWORD: {{ .Values.secret.smtpPassword | b64enc }}
  CELERY_BROKER_URL: {{ .Values.secret.celeryBrokerUrl | b64enc }}
  SENTRY_DSN: {{ default "" (b64enc .Values.secret.sentryDSN) }}
  INIT_PASSWORD: {{ default "" (b64enc .Values.secret.initPassword) }}
  HOSTED_OPENAI_API_KEY: {{ default "" (.Values.secret.hostedOpenAIKey | b64enc) }}
  LUNARY_PUBLIC_KEY: {{ default "" (b64enc .Values.secret.lunaryProjectID) }}
  CODE_EXECUTION_API_KEY: {{ default "" (b64enc .Values.secret.sandboxAPIKey) }}
  ENCRYPTION_PASSWORD: {{ default "" (b64enc .Values.backup.encryption.password) }}
{{- end }}
