apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  labels:
    {{- include "dify.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.sandboxPort }}
      targetPort: sandbox
      protocol: TCP
      name: sandbox
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    role: sandbox
