apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-plugin
  labels:
    {{- include "dify.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pluginPort }}
      targetPort: plugin
      protocol: TCP
      name: plugin
    - port: {{ .Values.service.pluginDebugPort }}
      targetPort: plugin-debug
      protocol: TCP
      name: plugin-debug
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    role: plugin
