apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-web
  labels:
    {{- include "dify.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    role: web
