apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "dify.fullname" . }}-upgrade"
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    role: upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        role: api
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 12}}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | trunc 12}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: pre-upgdrade-job
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["flask"]
          args:
            - db
            - upgrade
          envFrom:
            - configMapRef:
                name: {{ default (include "dify.fullname" .) .Values.global.dify.configName }}
            - secretRef:
                name: {{ default (include "dify.fullname" .) .Values.global.dify.secretName }}
