# helm repo add mattermost https://helm.mattermost.com
# helm upgrade mattermost-push-proxy -n chat mattermost/mattermost-push-proxy --version 0.14.3 -f mattermost-push-proxy/values.yaml -f mattermost-push-proxy/values.secret.yaml

image:
  repository: phntom/mattermost-push-proxy
  tag: "6.4.6@sha256:8c0ca7252c65f81c3d9d37b6049d1b896d0935095cba5ce7837ed899118ba5b5"
  pullPolicy: IfNotPresent

service:
  name: mattermost-push-proxy
  type: ClusterIP
  externalPort: 8065
  internalPort: 8066

sendTimeoutSec: 30
retryTimeoutSec: 8
enableMetrics: true

androidPushSettings:
  android:
    serviceFileLocation: "/mattermost-push-proxy/credentials/android"
    serviceFileName: "android-service-account.json"
    # serviceFile: provided in values.secret.yaml
  android_rn:
    serviceFileLocation: "/mattermost-push-proxy/credentials/android-rn"
    serviceFileName: "android-rn-service-account.json"
    # serviceFile: provided in values.secret.yaml
