apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
{{ include "firefly-iii.labels" . | indent 4 }}
type: Opaque
data:
  APP_ENV: {{ "local" | b64enc | quote }}
  APP_KEY: {{ default "appkey" .Values.fireflyiii.appKey | b64enc | quote }}
  APP_URL: {{ .Values.fireflyiii.url | b64enc | quote }}
  LOG_CHANNEL: {{ "stdout" | b64enc | quote }}
  APP_LOG_LEVEL: {{ "error" | b64enc | quote }}
  TRUSTED_PROXIES: {{ "**" | b64enc | quote }}
  DB_PORT: {{ .Values.fireflyiii.database.port | b64enc | quote }}
  DB_CONNECTION: {{ .Values.fireflyiii.database.type | b64enc | quote }}
  DB_HOST: {{ .Values.fireflyiii.database.host | b64enc | quote }}
  DB_DATABASE: {{ .Values.fireflyiii.database.database | b64enc | quote }}
  DB_USERNAME: {{ .Values.fireflyiii.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.fireflyiii.database.password | b64enc | quote }}
  {{ if .Values.fireflyiii.login.oauth2.enabled }}
  AUTHENTICATION_GUARD: {{ "remote_user_guard" | b64enc | quote }}
  AUTHENTICATION_GUARD_HEADER: {{ .Values.fireflyiii.login.oauth2.header | default "HTTP_X_AUTH_REQUEST_EMAIL" | b64enc | quote }}
  {{ end }}
  {{ if eq .Values.fireflyiii.login.provider "ldap" }}
  {{ if eq .Values.fireflyiii.login.ldap.type "OpenLDAP" }}
  LOGIN_PROVIDER: {{ .Values.fireflyiii.login.provider | b64enc | quote }}
  ADLDAP_CONNECTION_SCHEME: {{ .Values.fireflyiii.login.ldap.type | b64enc | quote }}
  ADLDAP_AUTO_CONNECT: {{ "true" | b64enc | quote }}
  ADLDAP_CONTROLLERS: {{ .Values.fireflyiii.login.ldap.host | b64enc | quote }}
  ADLDAP_PORT: {{ .Values.fireflyiii.login.ldap.port | b64enc | quote }}
  ADLDAP_TIMEOUT: {{ "5" | b64enc | quote }}
  ADLDAP_BASEDN: {{ .Values.fireflyiii.login.ldap.basedn | b64enc | quote }}
  ADLDAP_FOLLOW_REFFERALS: {{ "false" | b64enc | quote }}
  ADLDAP_USE_SSL: {{ "false" | b64enc | quote }}
  ADLDAP_USE_TLS: {{ "false" | b64enc | quote }}
  ADLDAP_ADMIN_USERNAME: {{ .Values.fireflyiii.login.ldap.admin.login | b64enc | quote }}
  ADLDAP_ADMIN_PASSWORD: {{ .Values.fireflyiii.login.ldap.admin.password | b64enc | quote }}
  ADLDAP_ACCOUNT_PREFIX: {{ .Values.fireflyiii.login.ldap.prefix | b64enc | quote }}
  ADLDAP_ACCOUNT_SUFFIX: {{ .Values.fireflyiii.login.ldap.suffix | b64enc | quote }}
  ADLDAP_PASSWORD_SYNC: {{ "false" | b64enc | quote }}
  ADLDAP_LOGIN_FALLBACK: {{ "false" | b64enc | quote }}
  ADLDAP_DISCOVER_FIELD: {{ "cn" | b64enc | quote }}
  ADLDAP_AUTH_FIELD: {{ "cn" | b64enc | quote }}
  ADLDAP_SYNC_FIELD: {{ "cn" | b64enc | quote }}
  {{ end }}
  {{ end }}
