apiVersion: v2
name: mindav
description: WebDAV interface to Google Cloud Storage
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
  - name: oauth2-proxy
    alias: oauth2proxy
    version: 3.2.15
    repository: https://phntom.kix.co.il/charts/
    condition: oauth2proxy.enable
